version: '3.9'

services:
  user:
    build: .
    restart: always
    container_name: user-microservice
    ports:
      - "18080:18080"
      - "50054:50054"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=user
    ports:
      - "7777:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфигурация Prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin  # Пароль для Grafana
    volumes:
      - ./etc/grafana/dashboards:/etc/grafana/provisioning/dashboards  # Дашборды
      - ./etc/grafana/datasources:/etc/grafana/provisioning/datasources  # Источники данных
      - grafana-storage:/var/lib/grafana  # Хранилище для Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: