DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS lectures CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS video_lectures CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
