// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	AirplaneMaterials string
	AirplaneModels    string
	Labs              string
	SchemaMigrations  string
}{
	AirplaneMaterials: "airplane_materials",
	AirplaneModels:    "airplane_models",
	Labs:              "labs",
	SchemaMigrations:  "schema_migrations",
}
