// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	AiLectures               string
	AiModels                 string
	AirplaneMaterialLectures string
	AirplaneMaterials        string
	AirplaneModels           string
	AnalysisResults          string
	DefectFindings           string
	DefectTypes              string
	Labs                     string
	LecturesAi               string
	MaterialAnalysisResults  string
	Recommendations          string
	SchemaMigrations         string
}{
	AiLectures:               "ai_lectures",
	AiModels:                 "ai_models",
	AirplaneMaterialLectures: "airplane_material_lectures",
	AirplaneMaterials:        "airplane_materials",
	AirplaneModels:           "airplane_models",
	AnalysisResults:          "analysis_results",
	DefectFindings:           "defect_findings",
	DefectTypes:              "defect_types",
	Labs:                     "labs",
	LecturesAi:               "lectures_ai",
	MaterialAnalysisResults:  "material_analysis_results",
	Recommendations:          "recommendations",
	SchemaMigrations:         "schema_migrations",
}
