// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Lab is an object representing the database table.
type Lab struct {
	ID      int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title   string `boil:"title" json:"title" toml:"title" yaml:"title"`
	Author  string `boil:"author" json:"author" toml:"author" yaml:"author"`
	Lecture string `boil:"lecture" json:"lecture" toml:"lecture" yaml:"lecture"`
	Formule string `boil:"formule" json:"formule" toml:"formule" yaml:"formule"`

	R *labR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L labL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LabColumns = struct {
	ID      string
	Title   string
	Author  string
	Lecture string
	Formule string
}{
	ID:      "id",
	Title:   "title",
	Author:  "author",
	Lecture: "lecture",
	Formule: "formule",
}

var LabTableColumns = struct {
	ID      string
	Title   string
	Author  string
	Lecture string
	Formule string
}{
	ID:      "labs.id",
	Title:   "labs.title",
	Author:  "labs.author",
	Lecture: "labs.lecture",
	Formule: "labs.formule",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var LabWhere = struct {
	ID      whereHelperint64
	Title   whereHelperstring
	Author  whereHelperstring
	Lecture whereHelperstring
	Formule whereHelperstring
}{
	ID:      whereHelperint64{field: "\"labs\".\"id\""},
	Title:   whereHelperstring{field: "\"labs\".\"title\""},
	Author:  whereHelperstring{field: "\"labs\".\"author\""},
	Lecture: whereHelperstring{field: "\"labs\".\"lecture\""},
	Formule: whereHelperstring{field: "\"labs\".\"formule\""},
}

// LabRels is where relationship names are stored.
var LabRels = struct {
	MaterialAnalysisResults string
}{
	MaterialAnalysisResults: "MaterialAnalysisResults",
}

// labR is where relationships are stored.
type labR struct {
	MaterialAnalysisResults MaterialAnalysisResultSlice `boil:"MaterialAnalysisResults" json:"MaterialAnalysisResults" toml:"MaterialAnalysisResults" yaml:"MaterialAnalysisResults"`
}

// NewStruct creates a new relationship struct
func (*labR) NewStruct() *labR {
	return &labR{}
}

func (r *labR) GetMaterialAnalysisResults() MaterialAnalysisResultSlice {
	if r == nil {
		return nil
	}
	return r.MaterialAnalysisResults
}

// labL is where Load methods for each relationship are stored.
type labL struct{}

var (
	labAllColumns            = []string{"id", "title", "author", "lecture", "formule"}
	labColumnsWithoutDefault = []string{"title", "author", "lecture", "formule"}
	labColumnsWithDefault    = []string{"id"}
	labPrimaryKeyColumns     = []string{"id"}
	labGeneratedColumns      = []string{}
)

type (
	// LabSlice is an alias for a slice of pointers to Lab.
	// This should almost always be used instead of []Lab.
	LabSlice []*Lab
	// LabHook is the signature for custom Lab hook methods
	LabHook func(context.Context, boil.ContextExecutor, *Lab) error

	labQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	labType                 = reflect.TypeOf(&Lab{})
	labMapping              = queries.MakeStructMapping(labType)
	labPrimaryKeyMapping, _ = queries.BindMapping(labType, labMapping, labPrimaryKeyColumns)
	labInsertCacheMut       sync.RWMutex
	labInsertCache          = make(map[string]insertCache)
	labUpdateCacheMut       sync.RWMutex
	labUpdateCache          = make(map[string]updateCache)
	labUpsertCacheMut       sync.RWMutex
	labUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var labAfterSelectMu sync.Mutex
var labAfterSelectHooks []LabHook

var labBeforeInsertMu sync.Mutex
var labBeforeInsertHooks []LabHook
var labAfterInsertMu sync.Mutex
var labAfterInsertHooks []LabHook

var labBeforeUpdateMu sync.Mutex
var labBeforeUpdateHooks []LabHook
var labAfterUpdateMu sync.Mutex
var labAfterUpdateHooks []LabHook

var labBeforeDeleteMu sync.Mutex
var labBeforeDeleteHooks []LabHook
var labAfterDeleteMu sync.Mutex
var labAfterDeleteHooks []LabHook

var labBeforeUpsertMu sync.Mutex
var labBeforeUpsertHooks []LabHook
var labAfterUpsertMu sync.Mutex
var labAfterUpsertHooks []LabHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Lab) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Lab) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Lab) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Lab) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Lab) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Lab) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Lab) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Lab) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Lab) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range labAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLabHook registers your hook function for all future operations.
func AddLabHook(hookPoint boil.HookPoint, labHook LabHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		labAfterSelectMu.Lock()
		labAfterSelectHooks = append(labAfterSelectHooks, labHook)
		labAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		labBeforeInsertMu.Lock()
		labBeforeInsertHooks = append(labBeforeInsertHooks, labHook)
		labBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		labAfterInsertMu.Lock()
		labAfterInsertHooks = append(labAfterInsertHooks, labHook)
		labAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		labBeforeUpdateMu.Lock()
		labBeforeUpdateHooks = append(labBeforeUpdateHooks, labHook)
		labBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		labAfterUpdateMu.Lock()
		labAfterUpdateHooks = append(labAfterUpdateHooks, labHook)
		labAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		labBeforeDeleteMu.Lock()
		labBeforeDeleteHooks = append(labBeforeDeleteHooks, labHook)
		labBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		labAfterDeleteMu.Lock()
		labAfterDeleteHooks = append(labAfterDeleteHooks, labHook)
		labAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		labBeforeUpsertMu.Lock()
		labBeforeUpsertHooks = append(labBeforeUpsertHooks, labHook)
		labBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		labAfterUpsertMu.Lock()
		labAfterUpsertHooks = append(labAfterUpsertHooks, labHook)
		labAfterUpsertMu.Unlock()
	}
}

// One returns a single lab record from the query.
func (q labQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Lab, error) {
	o := &Lab{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for labs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Lab records from the query.
func (q labQuery) All(ctx context.Context, exec boil.ContextExecutor) (LabSlice, error) {
	var o []*Lab

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to Lab slice")
	}

	if len(labAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Lab records in the query.
func (q labQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count labs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q labQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if labs exists")
	}

	return count > 0, nil
}

// MaterialAnalysisResults retrieves all the material_analysis_result's MaterialAnalysisResults with an executor.
func (o *Lab) MaterialAnalysisResults(mods ...qm.QueryMod) materialAnalysisResultQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"material_analysis_results\".\"lab_id\"=?", o.ID),
	)

	return MaterialAnalysisResults(queryMods...)
}

// LoadMaterialAnalysisResults allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (labL) LoadMaterialAnalysisResults(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLab interface{}, mods queries.Applicator) error {
	var slice []*Lab
	var object *Lab

	if singular {
		var ok bool
		object, ok = maybeLab.(*Lab)
		if !ok {
			object = new(Lab)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLab)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLab))
			}
		}
	} else {
		s, ok := maybeLab.(*[]*Lab)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLab)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLab))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &labR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &labR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`material_analysis_results`),
		qm.WhereIn(`material_analysis_results.lab_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load material_analysis_results")
	}

	var resultSlice []*MaterialAnalysisResult
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice material_analysis_results")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on material_analysis_results")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for material_analysis_results")
	}

	if len(materialAnalysisResultAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MaterialAnalysisResults = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &materialAnalysisResultR{}
			}
			foreign.R.Lab = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.LabID) {
				local.R.MaterialAnalysisResults = append(local.R.MaterialAnalysisResults, foreign)
				if foreign.R == nil {
					foreign.R = &materialAnalysisResultR{}
				}
				foreign.R.Lab = local
				break
			}
		}
	}

	return nil
}

// AddMaterialAnalysisResults adds the given related objects to the existing relationships
// of the lab, optionally inserting them as new records.
// Appends related to o.R.MaterialAnalysisResults.
// Sets related.R.Lab appropriately.
func (o *Lab) AddMaterialAnalysisResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MaterialAnalysisResult) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.LabID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"material_analysis_results\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"lab_id"}),
				strmangle.WhereClause("\"", "\"", 2, materialAnalysisResultPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.LabID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &labR{
			MaterialAnalysisResults: related,
		}
	} else {
		o.R.MaterialAnalysisResults = append(o.R.MaterialAnalysisResults, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &materialAnalysisResultR{
				Lab: o,
			}
		} else {
			rel.R.Lab = o
		}
	}
	return nil
}

// SetMaterialAnalysisResults removes all previously related items of the
// lab replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Lab's MaterialAnalysisResults accordingly.
// Replaces o.R.MaterialAnalysisResults with related.
// Sets related.R.Lab's MaterialAnalysisResults accordingly.
func (o *Lab) SetMaterialAnalysisResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MaterialAnalysisResult) error {
	query := "update \"material_analysis_results\" set \"lab_id\" = null where \"lab_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.MaterialAnalysisResults {
			queries.SetScanner(&rel.LabID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Lab = nil
		}
		o.R.MaterialAnalysisResults = nil
	}

	return o.AddMaterialAnalysisResults(ctx, exec, insert, related...)
}

// RemoveMaterialAnalysisResults relationships from objects passed in.
// Removes related items from R.MaterialAnalysisResults (uses pointer comparison, removal does not keep order)
// Sets related.R.Lab.
func (o *Lab) RemoveMaterialAnalysisResults(ctx context.Context, exec boil.ContextExecutor, related ...*MaterialAnalysisResult) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.LabID, nil)
		if rel.R != nil {
			rel.R.Lab = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("lab_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.MaterialAnalysisResults {
			if rel != ri {
				continue
			}

			ln := len(o.R.MaterialAnalysisResults)
			if ln > 1 && i < ln-1 {
				o.R.MaterialAnalysisResults[i] = o.R.MaterialAnalysisResults[ln-1]
			}
			o.R.MaterialAnalysisResults = o.R.MaterialAnalysisResults[:ln-1]
			break
		}
	}

	return nil
}

// Labs retrieves all the records using an executor.
func Labs(mods ...qm.QueryMod) labQuery {
	mods = append(mods, qm.From("\"labs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"labs\".*"})
	}

	return labQuery{q}
}

// FindLab retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLab(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Lab, error) {
	labObj := &Lab{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"labs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, labObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from labs")
	}

	if err = labObj.doAfterSelectHooks(ctx, exec); err != nil {
		return labObj, err
	}

	return labObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Lab) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no labs provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(labColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	labInsertCacheMut.RLock()
	cache, cached := labInsertCache[key]
	labInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			labAllColumns,
			labColumnsWithDefault,
			labColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(labType, labMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(labType, labMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"labs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"labs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into labs")
	}

	if !cached {
		labInsertCacheMut.Lock()
		labInsertCache[key] = cache
		labInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Lab.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Lab) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	labUpdateCacheMut.RLock()
	cache, cached := labUpdateCache[key]
	labUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			labAllColumns,
			labPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update labs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"labs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, labPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(labType, labMapping, append(wl, labPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update labs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for labs")
	}

	if !cached {
		labUpdateCacheMut.Lock()
		labUpdateCache[key] = cache
		labUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q labQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for labs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for labs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LabSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"labs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, labPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in lab slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all lab")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Lab) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no labs provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(labColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	labUpsertCacheMut.RLock()
	cache, cached := labUpsertCache[key]
	labUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			labAllColumns,
			labColumnsWithDefault,
			labColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			labAllColumns,
			labPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert labs, could not build update column list")
		}

		ret := strmangle.SetComplement(labAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(labPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert labs, could not build conflict column list")
			}

			conflict = make([]string, len(labPrimaryKeyColumns))
			copy(conflict, labPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"labs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(labType, labMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(labType, labMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert labs")
	}

	if !cached {
		labUpsertCacheMut.Lock()
		labUpsertCache[key] = cache
		labUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Lab record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Lab) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no Lab provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), labPrimaryKeyMapping)
	sql := "DELETE FROM \"labs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from labs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for labs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q labQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no labQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from labs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for labs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LabSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(labBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"labs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, labPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from lab slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for labs")
	}

	if len(labAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Lab) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLab(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LabSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LabSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"labs\".* FROM \"labs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, labPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in LabSlice")
	}

	*o = slice

	return nil
}

// LabExists checks if the Lab row exists.
func LabExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"labs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if labs exists")
	}

	return exists, nil
}

// Exists checks if the Lab row exists.
func (o *Lab) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LabExists(ctx, exec, o.ID)
}
