// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Permissions      string
	PhotoURL         string
	Roles            string
	RolesPermissions string
	SchemaMigrations string
	Tokens           string
	Users            string
	UsersRoles       string
}{
	Permissions:      "permissions",
	PhotoURL:         "photo_url",
	Roles:            "roles",
	RolesPermissions: "roles_permissions",
	SchemaMigrations: "schema_migrations",
	Tokens:           "tokens",
	Users:            "users",
	UsersRoles:       "users_roles",
}
