-- +goose Up
CREATE TABLE IF NOT EXISTS labs
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   text not null,
    author  uuid not null,
    lecture text not null,
    formule text not null
);

-- Добавляем фейковые данные
INSERT INTO labs (title, author, lecture, formule)
VALUES ('Лабораторная работа по физике', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '<h1>что-то</h1><p><strong>Таблица</strong> (от лат. tabula — доска) — <strong>способ структурирования данных</strong>, который предполагает распределение информации по однотипным строкам и столбцам (графам). &nbsp;1</p><p style="text-align: left"><strong>Некоторые элементы таблицы</strong>:</p><ul><li><p><strong>Строки</strong>. В них сравниваются между собой какие-либо элементы: отметки, значения температуры воздуха или воды, стоимость, количество и т. д..&nbsp;3</p></li><li><p><strong>Столбцы</strong>. Отражают свойства, по которым происходит сравнение: пол, возраст, город и т. д..&nbsp;3</p></li><li><p><strong>Заголовок таблицы</strong>. Определяет название или назначение таблицы.&nbsp;3</p></li><li><p><strong>Ячейка</strong>. Находится на пересечении строки и столбца, содержит информацию в числовом, текстовом или другом виде.&nbsp;3</p></li></ul><p style="text-align: left">Таблицы широко используются в различных исследованиях и анализе данных. Встречаются в СМИ, в рукописных материалах, в компьютерных программах и в дорожных знаках.&nbsp;14sadfsadf</p><img class="editor-image" style="max-width: 100%; height: auto;" src="https://cdn1.ozone.ru/s3/multimedia-d/c600/6278532805.jpg"><table class="editor-table" style="min-width: 75px"><colgroup><col style="min-width: 25px"><col style="width: 25px"><col style="min-width: 25px"></colgroup><tbody><tr><th colspan="1" rowspan="1"><p></p></th><th colspan="1" rowspan="1" colwidth="25"><p style="text-align: center"></p></th><th colspan="1" rowspan="1"><p></p></th></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1" colwidth="25"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1" colwidth="25"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr></tbody></table>', 'F = m*a'),
       ('Лабораторная работа по химии', 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Органическая химия',
        'C6H12O6 → 2C2H5OH + 2CO2'),
       ('Лабораторная работа по математике', 'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'Дифференциальные уравнения',
        'dy/dx = k*y');
