apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Применяем правильный адрес для Prometheus в Docker
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"