CREATE TABLE IF NOT EXISTS courses
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT         NOT NULL,
    photo_url   TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS video_lectures
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses (id) NOT NULL,
    url       TEXT                           NOT NULL
);

CREATE TABLE modules
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    course_id BIGINT       NOT NULL,
    FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lectures
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(100)                   NOT NULL,
    module_id BIGINT REFERENCES modules (id) NOT NULL,
    lecture   TEXT                           NOT NULL
);

CREATE TABLE IF NOT EXISTS tests
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    lecture_id BIGINT       NOT NULL,
    FOREIGN KEY (lecture_id) REFERENCES lectures (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    TEXT   NOT NULL,
    test_id BIGINT NOT NULL,
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answers
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        TEXT    NOT NULL,
    is_correct  BOOLEAN NOT NULL,
    question_id BIGINT  NOT NULL,
    FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_courses
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role TEXT                           NOT NULL,
    user_uuid uuid                           NOT NULL,
    course_id BIGINT REFERENCES courses (id) NOT NULL
);

INSERT INTO courses (name, description, photo_url)
VALUES ('тестовый курс', 'тестовое описание', 'tmp/file.jpg');

INSERT INTO modules (name, course_id)
VALUES ('модуль 1', 1);
INSERT INTO modules (name, course_id)
VALUES ('модуль 2', 1);

INSERT INTO lectures (title, module_id, lecture)
VALUES ('лекция 1', 1, '');
INSERT INTO lectures (title, module_id, lecture)
VALUES ('лекция 2', 1,
        '<h1>что-то</h1><p><strong>Таблица</strong> (от лат. tabula — доска) — <strong>способ структурирования данных</strong>, который предполагает распределение информации по однотипным строкам и столбцам (графам). &nbsp;1</p><p style="text-align: left"><strong>Некоторые элементы таблицы</strong>:</p><ul><li><p><strong>Строки</strong>. В них сравниваются между собой какие-либо элементы: отметки, значения температуры воздуха или воды, стоимость, количество и т. д..&nbsp;3</p></li><li><p><strong>Столбцы</strong>. Отражают свойства, по которым происходит сравнение: пол, возраст, город и т. д..&nbsp;3</p></li><li><p><strong>Заголовок таблицы</strong>. Определяет название или назначение таблицы.&nbsp;3</p></li><li><p><strong>Ячейка</strong>. Находится на пересечении строки и столбца, содержит информацию в числовом, текстовом или другом виде.&nbsp;3</p></li></ul><p style="text-align: left">Таблицы широко используются в различных исследованиях и анализе данных. Встречаются в СМИ, в рукописных материалах, в компьютерных программах и в дорожных знаках.&nbsp;14</p><img class="editor-image" style="max-width: 100%; height: auto;" src="https://cdn1.ozone.ru/s3/multimedia-d/c600/6278532805.jpg"><table class="editor-table" style="min-width: 75px"><colgroup><col style="min-width: 25px"><col style="width: 25px"><col style="min-width: 25px"></colgroup><tbody><tr><th colspan="1" rowspan="1"><p></p></th><th colspan="1" rowspan="1" colwidth="25"><p style="text-align: center"></p></th><th colspan="1" rowspan="1"><p></p></th></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1" colwidth="25"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1" colwidth="25"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr></tbody></table>');
INSERT INTO lectures (title, module_id, lecture)
VALUES ('лекция 3', 2, '');

INSERT INTO tests (name, lecture_id)
VALUES ('Тестирование', 2);

INSERT INTO questions (text, test_id)
VALUES ('вопрос 1', 1);

INSERT INTO answers (text, is_correct, question_id)
VALUES ('ответ 1', true, 1);
INSERT INTO answers (text, is_correct, question_id)
VALUES ('ответ 2', false, 1);

-- Пример генерации 10 курсов по материаловедению
DO
$$
    BEGIN
        FOR i IN 1..10
            LOOP
                INSERT INTO courses (name, description, photo_url)
                VALUES ('Материаловедение ' || i,
                        'Описание курса по материаловедению №' || i,
                        'https://example.com/materials/image' || i || '.jpg');

                -- добавим по 2 модуля на курс
                FOR m IN 1..2
                    LOOP
                        INSERT INTO modules (name, course_id)
                        VALUES ('Модуль ' || m || ' курса ' || i,
                                currval('courses_id_seq') -- получаем ID только что вставленного курса
                               );

                        -- добавим по 2 лекции на модуль
                        FOR l IN 1..2
                            LOOP
                                INSERT INTO lectures (title, module_id, lecture)
                                VALUES ('Лекция ' || l || ' модуля ' || m || ' курса ' || i,
                                        currval('modules_id_seq'),
                                        '<p>Это содержимое лекции ' || l || ' по материаловедению.</p>');

                                -- тест к каждой второй лекции
                                IF l = 2 THEN
                                    INSERT INTO tests (name, lecture_id)
                                    VALUES ('Тест к лекции ' || l || ' модуля ' || m || ' курса ' || i,
                                            currval('lectures_id_seq'));

                                    -- 1 вопрос с 2 ответами
                                    INSERT INTO questions (text, test_id)
                                    VALUES ('Что такое сплав?',
                                            currval('tests_id_seq'));

                                    INSERT INTO answers (text, is_correct, question_id)
                                    VALUES ('Материал, состоящий из двух или более металлов', true,
                                            currval('questions_id_seq'));

                                    INSERT INTO answers (text, is_correct, question_id)
                                    VALUES ('Чистый металл без примесей', false, currval('questions_id_seq'));
                                END IF;

                            END LOOP;
                    END LOOP;
            END LOOP;
    END
$$;
