// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	SchemaMigrations string
	Tokens           string
	Users            string
}{
	SchemaMigrations: "schema_migrations",
	Tokens:           "tokens",
	Users:            "users",
}
