psql:
  user: "postgres"
  pass: "pass"
  host: "localhost"
  port: 6666
  dbname: "course"
  sslmode: "disable"
  blacklist:
    - test
    - gopg_migrations
    - db_version

mongo:
  host: "localhost"
  port: 27017
  user: "mongo"
  pass: "pass"
