// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Answers          string
	Courses          string
	Lectures         string
	Modules          string
	Questions        string
	SchemaMigrations string
	Tests            string
	UsersCourses     string
	VideoLectures    string
}{
	Answers:          "answers",
	Courses:          "courses",
	Lectures:         "lectures",
	Modules:          "modules",
	Questions:        "questions",
	SchemaMigrations: "schema_migrations",
	Tests:            "tests",
	UsersCourses:     "users_courses",
	VideoLectures:    "video_lectures",
}
