// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Courses          string
	Lectures         string
	Modules          string
	Questions        string
	SchemaMigrations string
	Tests            string
	VideoLectures    string
}{
	Courses:          "courses",
	Lectures:         "lectures",
	Modules:          "modules",
	Questions:        "questions",
	SchemaMigrations: "schema_migrations",
	Tests:            "tests",
	VideoLectures:    "video_lectures",
}
