# This workflows will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./userMicroservice

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: user
        options: >-
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      MY_VARIABLE: ${{ vars.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy
          go build -v ./...
          mockgen -destination=mocks/postgres_mock.go -package=mocks -source=internal/adapters/postgres/interface.go

      - name: Print environment variable
        run: echo $MY_VARIABLE

      - name: Test
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
